language: node_js
  - "lts/*"
install:
  - yarn
script:
  - yarn export
after_script:
  - echo '' > out/.nojekyll
  - echo $CNAME > out/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: out
  keep-history: true
  on:
    branch: master
