language: node_js
  - "lts/*"
install:
  - yarn
script:
  - export BUILD_FOLDER=$BUILD_FOLDER yarn export
after_success:
  - echo '' > $BUILD_FOLDER/.nojekyll
  - echo $CNAME > $BUILD_FOLDER/CNAME
  - ./bin/buildSitemap.js
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: $BUILD_FOLDER
  keep-history: true
  on:
    branch: master
